# Generated by Django 4.0.4 on 2022-07-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'descuento',
                'verbose_name_plural': 'descuentos',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='active',
        ),
    ]
