# Generated by Django 4.0.4 on 2022-07-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discount_remove_products_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='price',
        ),
    ]
